### PR TITLE
Update jitter.Rd

### PR DESCRIPTION
**Pull request by elinw**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
@elinw this is a 'read-only' mirror to read. study, test, ... R sources.  

To actually submitt a change you should probably still go via bugzilla.

**Comment by jeroen** [comment]
I think she knows :)

**Comment by eddelbuettel** [comment]
All good then :)

**Comment by elinw** [comment]
Wow a seg fault!

**Comment by jeroen** [comment]
The macos segfault is unrelated to this PR. It will disappear when you rebase on master. (the r checks seems to crash on macos 11.0 so I downgraded the workflow to macos 10.15)

**Pull request closed without merging**
