### PR TITLE
Fix 0x...L parse data

### PR DESCRIPTION
**Pull request by krlmlr**
for https://github.com/r-lib/styler/issues/760.

### CODE REVIEW

**Comment by jeroen** [comment]
Looks like this broke some tests...

**Comment by krlmlr** [comment]
Good catch, thanks! I wonder why I didn't receive an e-mail notification for my PR.

**Comment by lorenzwalthert** [comment]
Now we got a merge conflict to resolve...

**Comment by krlmlr** [comment]
Merged in R-devel.

**Pull request closed without merging**
